language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update -qq
  - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab2_0.996-1.1_amd64.deb
  - sudo dpkg -i  libmecab2_0.996-1.1_amd64.deb
  - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab-dev_0.996-1.1_amd64.deb
  - sudo dpkg -i libmecab-dev_0.996-1.1_amd64.deb
  - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/mecab-utils_0.996-1.1_amd64.deb
  - sudo dpkg -i mecab-utils_0.996-1.1_amd64.deb
  - sudo apt-get install -y mecab-ipadic-utf8
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=mlask"
after_success:
  - coveralls
